// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.URLEncoder/Decoder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("result")]
        public string Result { get; set; }

        [JsonProperty("original_length")]
        public long OriginalLength { get; set; }

        [JsonProperty("result_length")]
        public long ResultLength { get; set; }
    }
}
